CREATE TABLE japan (
          id int primary key GENERATED by default as identity ,
          romadji varchar (255) not null,
          kanji varchar (255) not null,
          hiragana varchar (255) not null,
          translation varchar (255) not null
);

CREATE TABLE grammarnotes (
          id int primary key GENERATED by default as identity ,
          source varchar (255) not null,
          grammarrule varchar (255) not null,
          explanation  varchar (255) not null,
          example varchar (255) not null
);

CREATE TABLE person (
           id int primary key GENERATED by default as identity ,
           username varchar(100) not null,
           password varchar(100) not null,
           role varchar(100) not null
);


CREATE TABLE results (
            id int primary key GENERATED by default as identity ,
            user_id int references person (id) on delete set null,
            number_of_right_answers int,
            number_of_tasks int,
            date_time timestamp
);

CREATE TABLE failed_quiz_tasks (
            id int primary key GENERATED by default as identity,
            quiz_result_id int references results (id) on delete set null,
            failed_question varchar(255) not null
);


INSERT INTO japan (romadji, kanji, hiragana, translation)
values ('koohii', 'コーヒー', 'コーヒー', 'кофе');
INSERT INTO japan (romadji, kanji, hiragana, translation)
values ('koohii no okawari', 'コーヒーのお代わり', 'コーヒーのおかわり', 'добавка кофе, еще чашка');
INSERT INTO japan (romadji, kanji, hiragana, translation)
values ('koohii ni shimasuka. Soretomo koucha ni shimasuka', 'コーヒーにしますか. それとも紅茶にしますか',
        'コーヒーにしますか. それともこうちゃにします か', 'сделать кофе? Или может чай?');
INSERT INTO japan (romadji, kanji, hiragana, translation)
values ('koohii funsaiki', 'コーヒー粉砕機',
        'コーヒーふんさいき', 'кофемолка');


INSERT INTO grammarnotes (source, grammarrule, explanation, example)
values ('II.1.2.4.', 'Глаг намерит форма + to shite iru',
        'Незадолго до этого изменения - скоро будет -присоединяется к мгновенным глаголам - формал',
        'Saa, kesshousen ga ima, hajimarou to shite imasu. Minna kinchoushite imasu.');
INSERT INTO grammarnotes (source, grammarrule, explanation, example)
values ('II.1.4.1./17./II.6.6.1.', 'Сущ + o hajime (to shite/ to suru сущ)',
        'Начиная от (один из примеров) - приводится конкретный пример - далее указывается общая категория - форм',
        'Kono taiikukan de wa suiei o hajime, iroirona supootsu ga tanoshimeru.');
INSERT INTO grammarnotes (source, grammarrule, explanation, example)
values ('I.1.13.6. / I.8.6.5.', 'Глаг слов форма/сущ (+ вспом + aru)/сущ+ ni aru + majiki + сущ',
        'С этой позиции морально думая - нельзя. Вначале - позиция. Форм. После обязательно сущ, только в привычных формах.',
        'Kore wa, ko o motsu oya to shite yurusu majiki hanzai de aru.');

INSERT INTO person (username, password, role) values ('user',
'$2a$10$rCKjb9wIwIZXgUK0qjctqeRaUj5nTS2ULY2etxkE/m.d9gviDir6q', 'ROLE_GUEST');
INSERT INTO person (username, password, role) values ('admin',
'$2a$10$rCZoQRt8t8qW5aCDBHDrauTvu/24K5Py2f0/0.9iXQLeiuXqv4bqq', 'ROLE_ADMIN');
INSERT INTO person (username, password, role) values ('user2',
'$2a$10$GTa16adnOfwZaUAvdN7KHefjSXYxN9RY1cwbNQJf5pW9K7Jzscbbm', 'ROLE_USER');


INSERT INTO results (user_id, number_of_right_answers, number_of_tasks, date_time) values
(1, 1, 2, '2023-09-04 23:25:28.986024');
INSERT INTO results (user_id, number_of_right_answers, number_of_tasks, date_time) values
(1, 2, 5, '2023-09-05 23:25:28.986024');
INSERT INTO results (user_id, number_of_right_answers, number_of_tasks, date_time) values
(1, 3, 7, '2023-09-06 23:25:28.986024');
INSERT INTO results (user_id, number_of_right_answers, number_of_tasks, date_time) values
(1, 4, 5, '2023-09-07 23:25:28.986024');
INSERT INTO results (user_id, number_of_right_answers, number_of_tasks, date_time) values
(3, 5, 5, '2023-09-08 23:25:28.986024');
INSERT INTO results (user_id, number_of_right_answers, number_of_tasks, date_time) values
(3, 6, 8, '2023-09-09 23:25:28.986024');


INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(1, 'failed quiz task 1 1');
INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(2, 'failed quiz task 2 1');
INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(2, 'failed quiz task 2 2');
INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(2, 'failed quiz task 2 3');
INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(3, 'failed quiz task 3 1');
INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(3, 'failed quiz task 3 2');
INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(3, 'failed quiz task 3 3');
INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(3, 'failed quiz task 3 4');
INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(4, 'failed quiz task 4 1');
INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(6, 'failed quiz task 6 1');
INSERT INTO failed_quiz_tasks (quiz_result_id, failed_question) VALUES
(6, 'failed quiz task 6 2');








